### ISSUE TITLE
添加api 19的支持

### ISSUE THREAD

**Issue by rrrfff** [rk700/VirtualHook#14]
想添加android 4.4.4的支持, 会不会很困难?问题好像在于YAHFA?

另外, 在5.0.0测试发现, 只要在/sdcard/io.virtualhook下放你提供的apk, 比如demoPlugin或者ChangePhoneInfo或者CertUnpinning, 都会导致以下native异常:
F/libc    ( 6776): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x28 in tid 6807 (Thread-353)
I/DEBUG   (   75): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (   75): Build fingerprint: 'generic/vbox86p/vbox86p:5.0/LRX21M/genymotion08251046:userdebug/test-keys'
I/DEBUG   (   75): Revision: '0'
I/DEBUG   (   75): ABI: 'x86'
I/DEBUG   (   75): pid: 6776, tid: 6807, name: Thread-353  >>> com.jingdong.pdj:guard <<<
I/DEBUG   (   75): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x28
I/DEBUG   (   75):     eax 00000028  ebx f1466a20  ecx f12ceff4  edx 00000028
I/DEBUG   (   75):     esi 00000e59  edi 00000000
I/DEBUG   (   75):     xcs 00000023  xds 0000002b  xes 0000002b  xfs 0000009f  xss 0000002b
I/DEBUG   (   75):     eip f105ccef  ebp 000000c6  esp 1014bee4  flags 00210246
I/DEBUG   (   75):
I/DEBUG   (   75): backtrace:
I/DEBUG   (   75):     #00 pc 000afcef  /system/lib/libhoudini.so
I/DEBUG   (   75):
I/DEBUG   (   75): Tombstone written to: /data/tombstones/tombstone_02

**Comment by wjy000** [comment]
@rrrfff  去搜索一个叫 oneHook的项目,就是利用dexposed和yahfa做的4.0-7.0的hook

**Comment by rrrfff** [comment]
@wjy000 问题在于YAHFA, 我换了hook库就可以了

**Comment by wjy000** [comment]
@rrrfff yahfa不会支持4.4的,我觉得也没必要,5.0以下系统可以放弃了

**Comment by rk700** [comment]
https://github.com/rk700/YAHFA/issues/5

不考虑支持

**Comment by rrrfff** [comment]
@rk700 本来就没打算让yahfa支持,本来使用就有问题
