### ISSUE TITLE
关于VA版本的问题

### ISSUE THREAD

**Issue by wjy000** [rk700/VirtualHook#18]
最新版的va还是有很多优点的,但是我不知道virtualhook修改了va哪些东西,我自己升级va总是无法成功hook,麻烦大神抽个空更新一下va的版本吧,非常感谢

**Comment by rk700** [comment]
VirtualApp有一段时间没有更新了，目前VirtualHook与上游只相差1个commit:
https://github.com/rk700/VirtualHook/commit/17fc81c628594ecd2194cba774f1780c2047abbf
https://github.com/asLody/VirtualApp/commit/17fc81c628594ecd2194cba774f1780c2047abbf
不清楚你指的最新版VirtualApp是什么
