### ISSUE TITLE
get error when build apk

### ISSUE THREAD

**Issue by xuzc** [rk700/VirtualHook#20]
![image](https://user-images.githubusercontent.com/6511766/27892920-e888ff00-6234-11e7-8567-fd834222efff.png)

I'm new to jni, what can i do to fix it?

**Comment by rk700** [comment]
syscall是头文件<sys/syscall.h>中的，可能是NDK环境没配好

**Comment by rk700** [comment]
Android NDK更新到15后也出现了这样的问题

**Comment by rk700** [comment]
已修复 https://github.com/rk700/VirtualHook/commit/9ac0b6e288e365eeda7c4c5a252b5975f1962601

**Comment by xuzc** [comment]
thx very much
