### ISSUE TITLE
cannot use in Android 7.0

### ISSUE THREAD

**Issue by zjgooddream** [rk700/VirtualHook#23]
Hello, i cloned and compiled VirtualHook in Android Studio, install app in Samsung S7(Android 7.0),and push demoHookPlugin.apk to /sdcard/, install demoHookPlugin.apk with VirtualApp, but it cannot work at all, i cannot start demoHookPlugin.apk.

**Comment by rk700** [comment]
`demoHookPlugin.apk` is a just a hook apk and should not be installed. Push it to folder `/sdcard/io.virtualhook/` and install some other apps.

**Comment by zjgooddream** [comment]
thans a lot, got it!
