### ISSUE TITLE
大神,加了hook之后,市面上几乎所有的app运行没多久都会闪退

### ISSUE THREAD

**Issue by dq168dq** [rk700/VirtualHook#24]
大神,加了hook之后,市面上几乎所有的app运行没多久都会闪退,
如果去掉/mnt/shell/emulated/0/io.virtualhook中所有的apk,则能正常使用,那么这个hook就没啥实际意义了呀,求大神指教一二.

**Comment by dq168dq** [comment]
ps:只要随便hook一个函数,大多数应用就会闪退,测试了的应用有 微信、老虎地图、高德地图,求大神指点这怎么破.

**Comment by rk700** [comment]
提供具体信息，包括但不限于：
设备信息
系统版本
目标应用名称、版本
hook代码
崩溃日志

**Comment by rk700** [comment]
与 https://github.com/rk700/VirtualHook/issues/25 重复
