### ISSUE TITLE
大神,这是具体信息

### ISSUE THREAD

**Issue by dq168dq** [rk700/VirtualHook#25]
设备是红米2 4G联通版

系统是刷的android5.1.1 LMY47VMIUI8 7.6.8|开发版

目标应用有微信6.5.8,高德地图v8.1.0.2109

hook代码:

package lab.galaxy.changephoneinfo;

import android.content.ContentResolver;
import android.util.Log;

public class Hook_Secure_getAndroidID {

	public static String className = "android.provider.Settings$Secure";
	public static String methodName = "getString";
	public static String methodSig = "(Landroid/content/ContentResolver;Ljava/lang/String;)Ljava/lang/String;";

	private static int i = 0;

	public static String hook(Object thiz, ContentResolver resolver, String name) {
		Log.i("YAHFA", "Settings$Secure getString hooked");

		i++;
		Log.i("YAHFA2", "i=" + i);

		try {
			// TODO 此处为什么会发生异常? 说name的下标越界
			System.out.println("YAHFA2..." + name);
		} catch (Exception e) {
			Log.e("YAHFA2", e.getMessage(), e);
		}

		return "666666";
	}

}

异常信息:

07-11 12:01:57.519 32637-32637/io.virtualhook:p2 E/art: No implementation found for java.util.ArrayList com.tencent.mars.smc.SmcLogic.getLoadLibraries() (tried Java_com_tencent_mars_smc_SmcLogic_getLoadLibraries and 

Java_com_tencent_mars_smc_SmcLogic_getLoadLibraries__)
07-11 12:01:57.819 32637-32637/io.virtualhook:p2 W/linker: libtenpay_utils.so: unused DT entry: type 0x6ffffffe arg 0x3284
07-11 12:01:57.819 32637-32637/io.virtualhook:p2 W/linker: libtenpay_utils.so: unused DT entry: type 0x6fffffff arg 0x1
07-11 12:01:59.069 32637-32652/io.virtualhook:p2 I/art: Background sticky concurrent mark sweep GC freed 10440(667KB) AllocSpace objects, 8(128KB) LOS objects, 4% free, 18MB/19MB, paused 8.727ms total 54.973ms
07-11 12:01:59.089 32637-32637/io.virtualhook:p2 W/linker: libyahfa.so: unused DT entry: type 0x6ffffffe arg 0x4fc
07-11 12:01:59.089 32637-32637/io.virtualhook:p2 W/linker: libyahfa.so: unused DT entry: type 0x6fffffff arg 0x1
07-11 12:01:59.089 32637-32637/io.virtualhook:p2 I/YAHFA-Native: init to SDK 22
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err: android.system.ErrnoException: symlink failed: EEXIST (File exists)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at libcore.io.Posix.symlink(Native Method)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:189)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:397)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at $Proxy1.symlink(Unknown Source)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at android.system.Os.symlink(Os.java:474)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at com.lody.virtual.helper.utils.FileUtils.createSymlink(FileUtils.java:56)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at com.lody.virtual.client.VClientImpl.applyHookPlugin(VClientImpl.java:337)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:318)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:187)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:114)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:71)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at android.os.Looper.loop(Looper.java:135)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5296)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
07-11 12:01:59.109 32637-32637/io.virtualhook:p2 D/NativeEngine: DexOrJarPath = /sdcard/io.virtualhook/ChangePhoneInfo-debug.apk, OutputPath = /data/user/0/io.virtualhook/virtual/opt/ChangePhoneInfo-debug.dex.
07-11 12:01:59.119 32637-32705/io.virtualhook:p2 V/NFC: this device does not have NFC support
07-11 12:01:59.119 32637-32637/io.virtualhook:p2 W/linker: libhookprop.so: unused DT entry: type 0x6ffffffe arg 0x4d0
07-11 12:01:59.119 32637-32637/io.virtualhook:p2 W/linker: libhookprop.so: unused DT entry: type 0x6fffffff arg 0x2
07-11 12:01:59.119 32637-32637/io.virtualhook:p2 I/ChangePhoneInfo: native hook done

**Comment by dq168dq** [comment]
ps: 如果hook代码中,不去打印,也就是把这段注释掉,就不会闪退
		try {
			// TODO 此处为什么会发生异常? 说name的下标越界
			System.out.println("YAHFA2..." + name);
		} catch (Exception e) {
			Log.e("YAHFA2", e.getMessage(), e);
		}

**Comment by rk700** [comment]
2个问题
1. `getString(ContentResolver resolver, String name)` 是静态方法，调用时没有`this`对象，所以hook方法应该为`public static String hook(ContentResolver resolver, String name)`
2. 没有调用原方法，返回的内容可能有问题

**Comment by dq168dq** [comment]
问题解决了,谢谢大神.

**Comment by pangff** [comment]
> 问题解决了,谢谢大神.

怎么解决的
