### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by beanflight** [rk700/VirtualHook#26]
我想添加一个功能：映射存储至具体的目录，比如 '/mnt/sdcard/'映射到'/mnt/sdcard/VirtualHook/'，实现VirtualHook内应用和本机应用的存储读写完全相互隔离，不知道应该怎么处理，代码怎么实现？

**Comment by rk700** [comment]
VirtualApp已经自带了IO路径映射的功能。VClientImpl.java里有个方法`startIOUniformer()`，可以看到其中已经设置了一些重定向。如果需要设置自定义的映射，可调用`NativeEngine.redirectDirectory(mountPoint, vsPath);`将mountPoint的访问定向到vsPath

**Comment by beanflight** [comment]
我水平太有限了，尝试了几次都没有什么效果
