### ISSUE TITLE
push到sd卡，有个错误。请教下大神怎么解决？

### ISSUE THREAD

**Issue by feifeishen** [rk700/VirtualHook#27]
我就把https://github.com/rk700/ChangePhoneInfo。这个demo生成的apk，push到/sdcard/
就出现了如下问题
W/System.err( 7310): java.lang.ClassNotFoundException: lab.galaxy.yahfa.HookInfo

W/System.err( 7310): 	at java.lang.Class.classForName(Native Method)

W/System.err( 7310): 	at java.lang.Class.forName(Class.java:308)

W/System.err( 7310): 	at lab.galaxy.yahfa.HookMain.doHookDefault(HookMain.java:29)

W/System.err( 7310): 	at com.lody.virtual.client.VClientImpl.applyHookPlugin(VClientImpl.java:337)

W/System.err( 7310): 	at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:321)

W/System.err( 7310): 	at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:190)

W/System.err( 7310): 	at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:114)

W/System.err( 7310): 	at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:71)

W/System.err( 7310): 	at android.os.Handler.dispatchMessage(Handler.java:107)

W/System.err( 7310): 	at android.os.Looper.loop(Looper.java:194)

W/System.err( 7310): 	at android.app.ActivityThread.main(ActivityThread.java:5537)

W/System.err( 7310): 	at java.lang.reflect.Method.invoke(Native Method)

W/System.err( 7310): 	at java.lang.reflect.Method.invoke(Method.java:372)

W/System.err( 7310): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)

W/System.err( 7310): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

W/System.err( 7310): Caused by: java.lang.ClassNotFoundException: Didn't find class "lab.galaxy.yahfa.HookInfo" on path: DexPathList[[zip file "/data/user/0/io.virtualhook/virtual/data/app/lab.galaxy.changephoneinfo/base.apk"],nativeLibraryDirectories=[/data/user/0/io.virtualhook/virtual/data/app/lab.galaxy.changephoneinfo/lib, /vendor/lib, /system/lib]]

W/System.err( 7310): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

W/System.err( 7310): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)

W/System.err( 7310): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

W/System.err( 7310): 	... 15 more

W/System.err( 7310): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "lab.galaxy.yahfa.HookInfo" on path: DexPathList[[zip file "/data/app/com.example.myxposed-1/base.apk", zip file "/data/app/com.example.myxposed-1/base.apk"],nativeLibraryDirectories=[/data/user/0/io.virtualhook/virtual/data/app/com.example.myxposed/lib, /vendor/lib, /system/lib]]

D/OpenGLRenderer(  974): DrawFrameTask 0x5588ea3278, canUnblockUiThread 1, canDrawThisFrame 1

W/System.err( 7310): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

W/System.err( 7310): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)

D/Surface (  974): Surface::setBuffersDimensions(this=0x5588ec6f20,w=720,h=50)

W/System.err( 7310): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

W/System.err( 7310): 		... 16 more

W/System.err( 7310): 		Suppressed: java.lang.ClassNotFoundException: lab.galaxy.yahfa.HookInfo

W/System.err( 7310): 			at java.lang.Class.classForName(Native Method)

W/System.err( 7310): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)

W/System.err( 7310): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)

W/System.err( 7310): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

W/System.err( 7310): 			... 17 more

W/System.err( 7310): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by rk700** [comment]
没有找到类，看文件`/data/user/0/io.virtualhook/virtual/data/app/lab.galaxy.changephoneinfo/base.apk`是否存在，是否包含了类lab.galaxy.yahfa.HookInfo
