### ISSUE TITLE
想请教一下怎么hook的   

### ISSUE THREAD

**Issue by liupeng110** [rk700/VirtualHook#28]
一个普通的apk里面的一些函数想hook掉，要怎么弄  我看有virtualhook还有个yahfa 里面的plugin
编译这个plugin没有apk啊

**Comment by liupeng110** [comment]
这个流程能说下么，能不能做到 把普通apk打包进 项目里  然后在项目里面直接hook这个apk的函数？？？

**Comment by jiusanzhou** [comment]
@liupeng110  反編譯找到你要hook的函數，virtualhook編譯出apk 安裝， 然後寫yahfa插件來hook你的目標函數，rk的 repo有例子 自己去瞄一眼「自己看代碼啊！ 上來就提issues......」

**Comment by tzabcd** [comment]
运行virtualhook正常，生成了插件的apk，放到手机上的sdcard了，为什么在Apps In SDCARD里找不到呢？是不是还有什么诀窍，也不能说guide太简单，只能怪我们不会弄的水平太菜了啊

**Comment by rk700** [comment]
https://github.com/rk700/VirtualHook#usage
按照示例写一个hook插件apk，注意需要在AndroidManifest.xml中设置metadata，将hook插件apk放到sdcard下，然后添加hook

**Comment by liupeng110** [comment]
@jiusanzhou  多谢了，现在总算理顺了   
1. 编译virtualhook成apk（这个是主框架）
2.然后根据待hook的apk,写一个插件（要hook什么函数都在插件里）
3.先在1编译出的apk里 加载插件apk，然后继续在1里加载待hook的apk

之前看了没看懂，有个yahfa 还有个virtualhook  懵了，不知道流程是怎样的

**Comment by liupeng110** [comment]
@rk700  好的，多谢老大

**Comment by liupeng110** [comment]
@jiusanzhou     
@rk700     
这个hook插件可以不安装直接硬编码进virtualhook中么 我看给出的流程是需要先安装插件的
如果插件直接硬编码进，待hook的apk直接放assets目录  会很方便调试  要不然每次都需要重新安装插件

**Comment by rk700** [comment]
硬编码hook插件apk路径，可以修改VClientImpl.java中hook注入代码相关部分

**Comment by liupeng110** [comment]
老大有没有qq群方便交流啊 @rk700

**Comment by rk700** [comment]
没有的，github issues已足够，并且可以方便遇到同样问题的人

**Comment by liupeng110** [comment]
可以把plugin的代码整合进 virtualhook 这个项目里面吗  
把plugin打包成一个apk,另外加载 有点慢啊  
我是把plugin和待hook的apk都放在assets下 复制到/data/data/包名/file/  下面
然后自动加载两个apk  先plugin 加载再待hook的
没有见监听加载成功的接口  总是出问题   只有一个apk是加载正常   plugin加载不了  还老闪退。。。。

**Comment by liupeng110** [comment]
我直接把plugin的代码复制进virtual中 没有效果  ，把plugin的代码整合进 virtualhook 这个项目里面吗
@rk700  @jiusanzhou

**Comment by rk700** [comment]
因为classloader的原因，直接复制hook插件代码可能会有问题

**Comment by liupeng110** [comment]
@rk700 嗯，直接复制不行 不能正常加载plugin代码
    还有别的办法吗？如果能整合进去,开发起来会省事很多

**Comment by jiusanzhou** [comment]
@liupeng110 倒不觉得直接整合进去开发会省事，你应该是要打包出去吧。
动态的思路应该是比较好的，准备把Hook的代码， 通过动态配置进行加载

**Comment by liupeng110** [comment]
@jiusanzhou 编译打包都会省事很多  两个项目可以整合成一个项目    
能说下怎么动态配置加载的么哥们

**Comment by rk700** [comment]
硬编码牺牲了灵活性，对于正常用户来说动态加载hook插件是更合适的做法

如果你的hook是固定不变的当然可以硬编码，但也就限于自己使用

**Comment by liupeng110** [comment]
@rk700   一定程度上是牺牲了灵活性的,那可不可以都支持？

**Comment by liupeng110** [comment]
@rk700  一个项目就hook一个apk 
插件事先写好的，有变动可以通过 版本升级重新进行更新
这样直接硬编码进去,加载速度 应该会有提升吧

**Comment by liupeng110** [comment]
@rk700   一个项目就hook一个apk是很正常的需求啊 
逆向分析  拦截广告 各种都会很方便，
plugin硬编码进去,待hook的apk放assets下
每次直接build 一下  再开个instant run  时间节省的非常多

**Comment by rk700** [comment]
VirtualApp是将安装应用的选择权交给用户而非硬编码，VirtualHook也是选取了一致的方式，将hook插件的安装交给用户而非开发者。

所以不会支持。如果你有需求，可以自己根据VirtualApp的代码进行相应修改。

**Comment by liupeng110** [comment]
？？？
老大 这不是个hook框架么？

**Comment by rk700** [comment]
是的，xposed也没有硬编码hook插件

**Comment by liupeng110** [comment]
那你是怎样逆向的用这个  virtualhook？

**Comment by liupeng110** [comment]
另外，你这样就能确保一定 是用户安装的插件“？  初始化偷偷加载一个插件  用户不知道不是一样的么

**Comment by liupeng110** [comment]
我提的建议是方便开发调试啊

**Comment by rk700** [comment]
我没有get到你的点

xposed怎么用的？不就是写hook插件，安装，重启，运行应用么

那VirtualHook有什么区别？HTTPS强校验抓包，写个插件，push到sd卡，在VirtualHook中安装，运行目标应用；如果测下个应用，直接再添加到VirtualHook中就ok了。我为什么要每测一个应用都重新编译一次VirtualHook？

我实在不明白为什么要把hook和目标应用全部集成到VirtualHook中。什么叫框架？什么叫插件？

**Comment by liupeng110** [comment]
你真的没有get到我说的点   
逆向啊   肯定要多次调试的    你写的插件也要多次调试

**Comment by liupeng110** [comment]
重新编译一次,插件直接更新一次

**Comment by liupeng110** [comment]
整合进一起，调试插件  就非常方便了

**Comment by liupeng110** [comment]
算了，我自己改

**Comment by rk700** [comment]
用 https://github.com/rk700/YAHFA/issues/29 统一跟踪DexClassLoader的问题
