### ISSUE TITLE
hook时出现一个错误。Fatal signal 11 (SIGSEGV), code 2, fault addr 0x508d88ab in tid 17396

### ISSUE THREAD

**Issue by 16368728** [rk700/VirtualHook#29]
如下：
07-28 18:29:44.311 17396-17396/io.virtualhook:p0 A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x508d88ab in tid 17396 (om.qts.customer)
07-28 18:29:44.413 1342-1342/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-28 18:29:44.413 1342-1342/? I/DEBUG: Build fingerprint: 'Android-x86/android_x86/x86:5.1.1/LMY48Z/denglibo06021006:userdebug/test-keys'
07-28 18:29:44.413 1342-1342/? I/DEBUG: Revision: '0'
07-28 18:29:44.413 1342-1342/? I/DEBUG: ABI: 'x86'
07-28 18:29:44.413 1342-1342/? I/DEBUG: pid: 17396, tid: 17396, name: om.qts.customer  >>> com.qts.customer <<<
07-28 18:29:44.413 1342-1342/? I/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x508d88ab
07-28 18:29:44.418 1342-1342/? I/DEBUG:     eax bffceda8  ebx b3bfca8c  ecx bffcf840  edx b27120e0
07-28 18:29:44.419 1342-1342/? I/DEBUG:     esi 9090906f  edi bffceda8
07-28 18:29:44.420 1342-1342/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000007  xss 0000007b
07-28 18:29:44.421 1342-1342/? I/DEBUG:     eip b3a4b172  ebp bffcee30  esp bffced30  flags 00210246
07-28 18:29:44.421 1342-1342/? I/DEBUG: backtrace:
07-28 18:29:44.421 1342-1342/? I/DEBUG:     #00 pc 003dc172  /system/lib/libart.so (art::StackVisitor::WalkStack(bool)+210)
07-28 18:29:44.421 1342-1342/? I/DEBUG:     #01 pc 003ec91a  /system/lib/libart.so (_jobject* art::Thread::CreateInternalStackTrace<false>(art::ScopedObjectAccessAlreadyRunnable const&) const+90)
07-28 18:29:44.422 1342-1342/? I/DEBUG:     #02 pc 003879e4  /system/lib/libart.so (art::Throwable_nativeFillInStackTrace(_JNIEnv*, _jclass*)+52)
07-28 18:29:44.422 1342-1342/? I/DEBUG:     #03 pc 00000f3a  /data/dalvik-cache/x86/system@framework@boot.oat
07-28 18:29:44.442 1342-1342/? I/DEBUG: Tombstone written to: /data/tombstones/tombstone_00
07-28 18:29:44.449 1512-17430/system_process W/ActivityManager:   Force finishing activity 1 io.virtualhook/com.lody.virtual.client.stub.StubActivity$C0
07-28 18:29:44.451 1512-17430/system_process E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!

**Comment by rk700** [comment]
运行的是什么apk？执行到什么方法时崩溃？
