### ISSUE TITLE
vh的入口在哪里？

### ISSUE THREAD

**Issue by netstu** [rk700/VirtualHook#30]
1.包名必须为 lab.galaxy.yahfa吗？

2.HookInfo类的包名如果一定为 lab.galaxy.yahfa的话，其他类的包名也必须是这个包名吗？

3.我看了好几个demo，vh中自带的 demohookplugin只需要从sdcard添加即可。但有的demo下面写的是，需要push到 /sdcar/io.virtualhook/ 目录下。这两种方法到底是哪一种？

**Comment by rk700** [comment]
1. 包名不需要一定是lab.galaxy.yahfa

2. 现在是从hook插件中加载类lab.galaxy.yahfa.HookInfo，所以HookInfo类的包名必须是lab.galaxy.yahfa。其他类的包名可以是其他的

3. hook插件加载方式进行了更新，现在是将hook插件放在/sdcard/，然后手动添加hook插件。几个demo的README忘了更新

**Comment by z8806c** [comment]
如何手动添加 hook插件  加在哪个方法呢? 看VirtualHook DEMO没有加载插件
