### ISSUE TITLE
va昨天更新了，大概什么时候可以完成适配？

### ISSUE THREAD

**Issue by netstu** [rk700/VirtualHook#31]
Lody  11:23:21
@全体成员 昨天更新已支持最新所有加固，已兼容的应用包括12306，招商银行客户端。此外，最新版本app启动速度比原来会快70%。

**Comment by rk700** [comment]
1. VirtualHook使用substrate做native hook，不存在梆梆加固应用崩溃的问题
2. app启动优化未仔细分析

**Comment by netstu** [comment]
现在感觉启动app后特别卡，有时候能启动，有时候过一会就卡死，所以看看vh能否升级一下，看是否有好转

**Comment by rk700** [comment]
没有详细信息。

应用是什么？设备型号？系统版本？hook了什么内容？上游代码是否存在同样问题？
