### ISSUE TITLE
不能HOOK静态方法吗？

### ISSUE THREAD

**Issue by ws15621066586** [rk700/VirtualHook#33]

**Comment by rk700** [comment]
没有遇到这样的问题

具体代码是什么

**Comment by ws15621066586** [comment]
public class Hoo_Toast {
    public static String className = "android.widget.Toast";
    public static String methodName = "makeText";
    public static String methodSig = "(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;";
    public static Toast hook(Object thiz,Context a,CharSequence b,int c) {
        Toast.makeText(a,"00000000000000000",Toast.LENGTH_SHORT).show();
        return  origin(thiz,a,b,c);
    }
    public static Toast origin(Object thiz,Context a,CharSequence b,int c) {
        Log.d("dddd","ddddd");
        return null;
    }
}

**Comment by ws15621066586** [comment]
hook   maketoast   没有HOOK到，，我自已写了个静态方法好像也不能HOOK

**Comment by ws15621066586** [comment]
还有一问题愁了一天了，两进程交换数据，HOOK的方法就是别人PID，这跟单独两个APK交换数据还不一样！好不容易通过HOOK 得到了Context对像，动态注册了个广播，但是也接收不到，换成单独的APK却可以，vituralhook  两进程间有好的方法共享数据吗

**Comment by rk700** [comment]
hook代码的问题

`makeText()`是静态方法，传参没有`thiz`对象

#32

**Comment by ws15621066586** [comment]
vituralhook 两进程间有好的方法共享数据吗

**Comment by rk700** [comment]
不清楚，可以参考virtualapp
