### ISSUE TITLE
hook   Toast的makeText 方法总是闪退，下面是源码，这可能不是我的问题

### ISSUE THREAD

**Issue by ws15621066586** [rk700/VirtualHook#37]
public static String className = "android.widget.Toast";
    public static String methodName = "makeText";
    public static String methodSig = "(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;";
    public static Toast hook(Context a, CharSequence b, int c) {
        Toast toast=origin(a,b,c);
      // Toast.makeText(a,"00000000000000000",Toast.LENGTH_SHORT).show();
        return toast ;
    }
    public static Toast origin(Context a, CharSequence b, int c) {
        Log.d("dddd","ddddd");
        return null;
    }

**Comment by ws15621066586** [comment]
这么写，一运行别的APK就闪退，试了好几个都是，代码也看不出那有问题

**Comment by ws15621066586** [comment]
这么写，别的APK一有Toast就闪退，代码看不出有什么问题，麻烦作者看下，如果代码没有问题建议写个程序测试下

**Comment by rk700** [comment]
https://github.com/rk700/VirtualHook/commit/fca5dcbc37b3e3d39cff62e59134b5544a4d4261

**Comment by ws15621066586** [comment]
什么 意思，让我看C++源码吗，C++不大行

**Comment by ws15621066586** [comment]
可以了，，！！
