### ISSUE TITLE
能否支持多个hook用的apk，并修改成目录扫描的方式载入？

### ISSUE THREAD

**Issue by zjzdy** [rk700/VirtualHook#4]
自动载入的hook用的apk只支持/sdcard/io.virtualhook/patch.apk一个有点不方便。例如说我以前写了一个通用的patch1.apk来打印部分调用，后面要hook一个单独的新应用就必须在原来patch1的基础上修改，而不能单独写一个patch2.apk。这样添加也麻烦，移除也麻烦，做成模块化的样子就方便很多。如果做成模块化的话，直接扫描/sdcard/io.virtualhook/patch/*.apk，并自动添加就好了。（当然，如果你愿意搞成xposed install那样支持启用或禁用就更好，不过感觉写起来有点麻烦）

**Comment by wjy000** [comment]
和我想的一样

**Comment by rk700** [comment]
可以的，将某个文件夹下面的apk全部加载起来。原理上来讲，还可以写一个配置文件，对不同的应用采用不同的hook插件，当然这个实现起来就比较麻烦。现在可以先做简单加载全部插件这种

**Comment by rk700** [comment]
https://github.com/rk700/VirtualHook/commit/8d84bd95121eee3c49235a68fe8430650a0f57f3

将目录`/sdcard/io.virtualhook/`下的全部文件，都作为hook插件加载
