### ISSUE TITLE
能Hook 的DexFile的 loadClass 方法吗？

### ISSUE THREAD

**Issue by c1024** [rk700/VirtualHook#40]
我想Hook DexFile的 loadClass 方法。
代码如下
public class Hook_DexFile_loadClass {
    public static String className = "dalvik.system.DexFile";
    public static String methodName = "loadClass";
    public static String methodSig = "(Ljava/lang/String;Ljava/lang/ClassLoader;)Ljava/lang/Class;";
    public static Class hook( Object thiz, String name, ClassLoader loader) {

        Log.w("YAHFA", "load class " + name);
        return origin( thiz , name, loader);
    }

    public static Class origin(Object thiz, String name, ClassLoader loader) {
        Log.w("YAHFA", "should not be here");
        return null;
    }

插件加载后，没看到load class 日志信息 。是不能Hook吗

**Comment by dannyZhou** [comment]
在 lab.galaxy.yahfa.HookInfo 中有加上代码吗？ 如果说 没有 log， 说明 你的这个类根本没有加载。

**Comment by c1024** [comment]
@dannyZhou 有加

**Comment by rk700** [comment]
VirtualHook注入hook代码是在app创建之后，可能DexFile已经调用完成

**Comment by c1024** [comment]
Hook loadClassBinaryName 可以看到一些日志输出，但是感觉有些没有Hook到。DexFile的loadClass, loadClassBinaryName调用有的可能在Hook前已经完成

**Comment by rk700** [comment]
估计是这样的

VirtualHook在注入hook之前，相关的类加载已经完成
