### ISSUE TITLE
[issue] | 关于硬编码的问题

### ISSUE THREAD

**Issue by dannyZhou** [rk700/VirtualHook#41]
@rk700 
@liupeng110 （可能 @ 不到。。。）

### Reference:
- https://github.com/rk700/VirtualHook/issues/28 

关于硬编码的问题，在上面的 reference 中有过讨论，但是没有一个结果说如何来做。 

### Requirements:
- 取消 hookPlugin.apk , 直接讲 plugin 的代码写入到 yahfa 或者其他 module 中。
- 安装 apk 时候不需要另外单独安装 hookPlugin.apk 因为 代码已经写入 在项目中。 

### Try:
- 删除 通过 apk 创建 classLoader 的代码，hookPlugin 的代码放入 yahfa 中。

### Problem: 
- 这么做了之后， 运行出现异常， apk 崩溃。 

### Question:
- 怎么来实现？

**Comment by liupeng110** [comment]
@dannyZhou  @ 到了  
你那样我试过了不行
我是构建项目时候 写gradle脚本 生成到了框架assets下，加载时候先复制到内存卡，在加载plugin
最后再加载apk

**Comment by dannyZhou** [comment]
尝试1:

- 直接删除 classLoader 不可以，删除后， apk 报错， 错误从 native 层报出

尝试2:

- 自己写 classloader

```java
public class MyClassLoader extends ClassLoader {


    public MyClassLoader(ClassLoader parentClassLoader) {
        super(parentClassLoader);
    }

    @Override
    protected Class<?> findClass(String name) throws ClassNotFoundException {
        return Class.forName(name);
    }
}
```

出错，不能用。

**Comment by liupeng110** [comment]
从反馈来看，如果hook代码与目标处于不同classloader，可以正常hook；如果处于同一个classloader则会发生问题。rk700/VirtualHook#28
--

**Comment by liupeng110** [comment]
#26

**Comment by liupeng110** [comment]
合并 遍历合并后插件包名下所有类 用new classloader 加载

**Comment by rk700** [comment]
> 如果hook代码与目标处于不同classloader，可以正常hook；如果处于同一个classloader则会发生问题。

具体原因还不清楚

**Comment by rk700** [comment]
用 https://github.com/rk700/YAHFA/issues/29 统一跟踪DexClassLoader的问题
