### ISSUE TITLE
框架所有的东西都没改，只要HOOK某一方法，都没实际操作，只要在hook中调用origin 方法长时间运行就会无响应，输出下面的日志！

### ISSUE THREAD

**Issue by ws15621066586** [rk700/VirtualHook#44]
09-15 10:33:04.376 791-950/? E/NativeCrashListener: Exception dealing with report
                                                    android.system.ErrnoException: read failed: EAGAIN (Try again)
                                                        at libcore.io.Posix.readBytes(Native Method)
                                                        at libcore.io.Posix.read(Posix.java:147)
                                                        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
                                                        at android.system.Os.read(Os.java:364)
                                                        at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
                                                        at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)

**Comment by ws15621066586** [comment]
Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 10.  Wait queue head age: 9245.8ms.)
                                           Load: 24.3 / 24.41 / 21.0
                                           Android time :[2017-09-17 14:32:13.72] [3220.302]
                                           CPU usage from 7880ms to 2821ms ago:
                                             79% 789/system_server: 59% user + 19% kernel / faults: 3778 minor
                                             44% 1729/com.qihoo360.mobilesafe:GuardService: 35% user + 9.5% kernel / faults: 31697 minor 2 major
                                             20% 685/adbd: 5.5% user + 14% kernel / faults: 41 minor
                                             15% 1463/com.android.phone: 11% user + 4.1% kernel / faults: 383 minor
                                             15% 1011/com.android.systemui: 11% user + 3.7% kernel / faults: 571 minor
                                             9.1% 1261/com.qihoo360.mobilesafe.opti.powerctl:server: 7.3% user + 1.7% kernel / faults: 3826 minor
                                             8.3% 15387/com.cleanmaster.mguard_cn:worker: 5.9% user + 2.3% kernel / faults: 9280 minor
                                             7.1% 14790/com.ss.android.article.news: 4.9% user + 2.1% kernel / faults: 1264 minor
                                             6.3% 234/servicemanager: 2.5% user + 3.7% kernel
                                             5.1% 236/surfaceflinger: 2.5% user + 2.5% kernel
                                             4.1% 251/netd: 0.1% user + 3.9% kernel / faults: 1989 minor
                                             3.7% 15169/com.cleanmaster.mguard_cn:service: 2.9% user + 0.7% kernel / faults: 2769 minor
                                             3.5% 5208/com.androidmarket.dingzhi: 3.1% user + 0.3% kernel / faults: 57 minor
                                             3.5% 15296/com.cleanmaster.mguard_cn: 2.5% user + 0.9% kernel / faults: 4639 minor
                                             3.1% 2311/com.qihoo.cleandroid_cn:resident: 1.5% user + 1.5% kernel / faults: 1398 minor
                                             2.5% 284/zygote: 1.1% user + 1.3% kernel / faults: 11726 minor
                                             1.9% 8298/com.browser_llqhz: 0.7% user + 1.1% kernel / faults: 1775 minor 1 major
                                             1.5% 6606/com.qihoo.browser: 0.7% user + 0.7% kernel / faults: 3821 minor
                                             1.1% 768/gsm0710muxd: 0.5% user + 0.5% kernel
                                             1.1% 1598/kworker/1:3: 0% user + 1.1% kernel
                                             1.1% 27980/kworker/0:3: 0% user + 1.1% kernel
                                             0.3% 117/kworker/u17:1: 0% user + 0.3% kernel
                                             0.9% 233/lmkd: 0.3% user + 0.5% kernel
                                             0.9% 313/sdcard: 0% user + 0.9% kernel
                                             0.9% 1087/tx_thread: 0% user + 0.9% kernel
                                             0.9% 7887/com.amigo.keyguard: 0.3% user + 0.5% kernel / faults: 65 minor
                                             0.9% 15360/com.sankuai.meituan.dispatch.crowdsource:dppushservice: 0.1% user + 0.7% kernel / faults: 1224 minor
                                             0.9% 27095/gn.com.android.synchronizer: 0.5% user + 0.3% kernel / faults: 269 minor
                                             0.7% 140/mmcqd/0: 0% user + 0.7% kernel
                                             0.7% 268/mtk_agpsd: 0.3% user + 0.3% kernel / faults: 30 minor
                                             0.7% 833/mtkrild: 0.5% user + 0.1% kernel
                                             0.7% 1344/com.qihoo.browser:daemon: 0.3% user + 0.3% kernel / faults: 265 minor
                                             0.7% 1675/com.iflytek.inputmethod.assist: 0.3% user + 0.3% kernel / faults: 410 minor
                                             0.7% 2247/kworker/2:2: 0% user + 0.7% kernel
                                             0.7% 26177/kworker/0:0: 0% user + 0.7% kernel
                                             0.5% 180/kworker/4:1: 0% user + 0.5% kernel
                                             0.5% 272/mnld: 0.5% user + 0% kernel / faults: 64 minor
                                             0.5% 3420/com.qihoo360.mobilesafe.opti.powerctl:channel: 0.1% user + 0.3% kernel / faults: 1025 minor
                                             0.5% 4759/com.wandoujia.phoenix2:channel: 0.5% user + 0% kernel / faults: 19 minor
                                             0.5% 4979/com.eg.android.AlipayGphone: 0.5% user + 0% kernel / faults: 2 minor
                                             0.5% 5386/com.eg.android.AlipayGphone:push: 0.3% user + 0.1% kernel / faults: 1604 minor
                                             0.5% 18442/kworker/3:2: 0% user + 0.5% kernel
                                             0.3% 55/cfinteractive: 0% user + 0.3% kernel
                                             0.3% 56/kworker/5:1: 0% user + 0.3% kernel
                                             0.3% 89/hps_main: 0% user + 0.3% kernel
                                             0.3% 149/synaptics-tpd: 0% user + 0.3% kernel
                                             0.3% 1654/com.qihoo.browser:pushbrowser: 0.3% user + 0% kernel / faults: 13 minor
                                             0.3% 3606/com.wandoujia.phoenix2: 0.3% user + 0% kernel / faults: 537 minor
                                             0.3% 4277/com.qihoo360.mobilesafe.opti.powerctl: 0.3% user + 0% kernel / faults: 1061 minor
                                             0.3% 5205/tunman: 0% user + 0.3% kernel
                                             0.3% 8218/com.gionee.anti.stolen: 0.3% user + 0% kernel / faults: 743 minor
                                             0.3% 8241/com.gionee.account: 0.1% user + 0.1% kernel / faults: 371 minor
                                             0.3% 11653/kworker/u16:1: 0% user + 0.3% kernel
                                             0.1% 2

**Comment by ws15621066586** [comment]
com.lody.virtual.client.stub.StubActivity$C0), time=3214811
                                           Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 10.  Wait queue head age: 9245.8ms.)
                                           Load: 24.3 / 24.41 / 21.0
                                           Android time :[2017-09-17 14:32:13.72] [3220.302]
                                           CPU usage from 7880ms to 2821ms ago:
                                             79% 789/system_server: 59% user + 19% kernel / faults: 3778 minor
                                             44% 1729/com.qihoo360.mobilesafe:GuardService: 35% user + 9.5% kernel / faults: 31697 minor 2 major
                                             20% 685/adbd: 5.5% user + 14% kernel / faults: 41 minor
                                             15% 1463/com.android.phone: 11% user + 4.1% kernel / faults: 383 minor
                                             15% 1011/com.android.systemui: 11% user + 3.7% kernel / faults: 571 minor
                                             9.1% 1261/com.qihoo360.mobilesafe.opti.powerctl:server: 7.3% user + 1.7% kernel / faults: 3826 minor
                                             8.3% 15387/com.cleanmaster.mguard_cn:worker: 5.9% user + 2.3% kernel / faults: 9280 minor
                                             7.1% 14790/com.ss.android.article.news: 4.9% user + 2.1% kernel / faults: 1264 minor
                                             6.3% 234/servicemanager: 2.5% user + 3.7% kernel
                                             5.1% 236/surfaceflinger: 2.5% user + 2.5% kernel
                                             4.1% 251/netd: 0.1% user + 3.9% kernel / faults: 1989 minor
                                             3.7% 15169/com.cleanmaster.mguard_cn:service: 2.9% user + 0.7% kernel / faults: 2769 minor
                                             3.5% 5208/com.androidmarket.dingzhi: 3.1% user + 0.3% kernel / faults: 57 minor
                                             3.5% 15296/com.cleanmaster.mguard_cn: 2.5% user + 0.9% kernel / faults: 4639 minor
                                             3.1% 2311/com.qihoo.cleandroid_cn:resident: 1.5% user + 1.5% kernel / faults: 1398 minor
                                             2.5% 284/zygote: 1.1% user + 1.3% kernel / faults: 11726 minor
                                             1.9% 8298/com.browser_llqhz: 0.7% user + 1.1% kernel / faults: 1775 minor 1 major
                                             1.5% 6606/com.qihoo.browser: 0.7% user + 0.7% kernel / faults: 3821 minor
                                             1.1% 768/gsm0710muxd: 0.5% user + 0.5% kernel
                                             1.1% 1598/kworker/1:3: 0% user + 1.1% kernel
                                             1.1% 27980/kworker/0:3: 0% user + 1.1% kernel
                                             0.3% 117/kworker/u17:1: 0% user + 0.3% kernel
                                             0.9% 233/lmkd: 0.3% user + 0.5% kernel
                                             0.9% 313/sdcard: 0% user + 0.9% kernel
                                             0.9% 1087/tx_thread: 0% user + 0.9% kernel
                                             0.9% 7887/com.amigo.keyguard: 0.3% user + 0.5% kernel / faults: 65 minor
                                             0.9% 15360/com.sankuai.meituan.dispatch.crowdsource:dppushservice: 0.1% user + 0.7% kernel / faults: 1224 minor
                                             0.9% 27095/gn.com.android.synchronizer: 0.5% user + 0.3% kernel / faults: 269 minor
                                             0.7% 140/mmcqd/0: 0% user + 0.7% kernel
                                             0.7% 268/mtk_agpsd: 0.3% user + 0.3% kernel / faults: 30 minor
                                             0.7% 833/mtkrild: 0.5% user + 0.1% kernel
                                             0.7% 1344/com.qihoo.browser:daemon: 0.3% user + 0.3% kernel / faults: 265 minor
                                             0.7% 1675/com.iflytek.inputmethod.assist: 0.3% user + 0.3% kernel / faults: 410 minor
                                             0.7% 2247/kworker/2:2: 0% user + 0.7% kernel
                                             0.7% 26177/kworker/0:0: 0% user + 0.7% kernel
                                             0.5% 180/kworker/4:1: 0% user + 0.5% kernel
                                             0.5% 272/mnld: 0.5% user + 0% kernel / faults: 64 minor
                                             0.5% 3420/com.qihoo360.mobilesafe.opti.powerctl:channel: 0.1% user + 0.3% kernel / faults: 1025 minor
                                             0.5% 4759/com.wandoujia.phoenix2:channel: 0.5% user + 0% kernel / faults: 19 minor
                                             0.5% 4979/com.eg.android.AlipayGphone: 0.5% user + 0% kernel / faults: 2 minor
                                             0.5% 5386/com.eg.android.AlipayGphone:push: 0.3% user + 0.1% kernel / faults: 1604 minor
                                             0.5% 18442/kworker/3:2: 0% user + 0.5% kernel
                                             0.3% 55/cfinteractive: 0% user + 0.3% kernel
                                             0.3% 56/kworker/5:1: 0% user + 0.3% kernel
                                             0.3% 89/hps_main: 0% user + 0.3% kernel
                                             0.3% 149/synaptics-tpd: 0% user + 0.3% kernel
                                             0.3% 1654/com.qihoo.browser:pushbrowser: 0.3% user + 0% kernel / faults: 13 minor
                                             0.3% 3606/com.wandoujia.phoenix2: 0.3% user + 0% kernel / faults: 537 minor
                                             0.3% 4277/com.qihoo360.mobilesafe.opti.powerctl: 0.3% user + 0% kernel / faults: 1061 minor
                                             0.3% 5205/tunman: 0% user + 0.3% kernel
                                             0.3% 8218/com.gionee.anti.stolen: 0.3% user + 0% kernel / faults: 743 minor
                                             0.3% 8241/com.gionee.account: 0.1% user + 0.1% kernel / faults: 371 minor
                                             0.3% 11653/kworker/u16:1: 0% user + 0.3% kernel
                                             0.1% 2

**Comment by ws15621066586** [comment]
09-18 01:18:11.323 17858-17877/? E/art: 0xaaf3acf8 SpaceTypeMallocSpace begin=0x12c00000,end=0x1382c000,limit=0x32c00000,size=12MB,capacity=512MB,non_growth_limit_capacity=512MB,name="main rosalloc space"]
09-18 01:18:11.323 17858-17877/? E/art: 0xaafdc850 allocspace main rosalloc space live-bitmap 3[begin=0x12c00000,end=0x32c00000]
09-18 01:18:11.323 17858-17877/? E/art: 0xaaf44728 allocspace main rosalloc space mark-bitmap 3[begin=0x12c00000,end=0x32c00000]
09-18 01:18:11.323 17858-17877/? E/art: 0xaaf38680 SpaceTypeImageSpace begin=0x703ae000,end=0x7102d1e0,size=12MB,name="/data/dalvik-cache/arm/system@framework@boot.art"]
09-18 01:18:11.323 17858-17877/? E/art: 0xaaf38400 imagespace /data/dalvik-cache/arm/system@framework@boot.art live-bitmap 0[begin=0x703ae000,end=0x7102d200]
09-18 01:18:11.323 17858-17877/? E/art: 0xaaf38400 imagespace /data/dalvik-cache/arm/system@framework@boot.art live-bitmap 0[begin=0x703ae000,end=0x7102d200]
09-18 01:18:11.323 17858-17877/? E/art: 0xaafcb900 SpaceTypeZygoteSpace begin=0x7489f000,end=0x74a4b000,size=1712KB,name="Zygote space"]
09-18 01:18:11.323 17858-17877/? E/art: 0xaaf39a38 allocspace zygote / non moving space live-bitmap 0[begin=0x7489f000,end=0x74a4b000]
09-18 01:18:11.323 17858-17877/? E/art: 0xaaf39a38 allocspace zygote / non moving space live-bitmap 0[begin=0x7489f000,end=0x74a4b000]
09-18 01:18:11.323 17858-17877/? E/art: 0xab10b140 SpaceTypeMallocSpace begin=0x74a4b000,end=0x74d26000,limit=0x7889f000,size=2MB,capacity=62MB,non_growth_limit_capacity=62MB,name="alloc space"]
09-18 01:18:11.323 17858-17877/? E/art: 0xaaf992f8 allocspace alloc space live-bitmap 4[begin=0x74a4b000,end=0x7889f000]
09-18 01:18:11.323 17858-17877/? E/art: 0xaaf38638 allocspace alloc space mark-bitmap 4[begin=0x74a4b000,end=0x7889f000]
09-18 01:18:11.323 17858-17877/? E/art: 0xaaf3ce80 large object space:GcRetentionPolicyAlwaysCollect
09-18 01:18:11.323 17858-17877/? A/art: art/runtime/gc/space/large_object_space.cc:151] Attempted to free large object 0xab2bd000 which was not live

**Comment by ws15621066586** [comment]
最后一次发了，不知道原因就算了，我也不发了
E/art: 0xaaefdd88 allocspace main rosalloc space live-bitmap 3[begin=0x12c00000,end=0x32c00000]

下面是从网上找的原因：
实际的log很长，所以只截取了第一段；目前由于手头上能找到的资料太少，纠结了几天也没能解决，本人英语很糟糕，所以只在overflow和google上大概搜了一下，没有看到什么有启发的东西；最主要的是这个工程4.4.4的ART模式下是可以正常运行的，但是5.0却不行；由于看到是jclass引用的错误，感觉像是GC方面的问题。后来又在overflow上查了查，找到了关于android4.0之后的GC机制的改动，感觉和我遇到的问题很相似。于是将代码部分照此格式全部改正把所有   jclass a = env ->findclass(xxx);      的地方改成 jclass a ;          jclass tmp = env -> findclass(xxx);    a = (jclass)env->NewGlobalRef(tmp);  问题搞定~！！！

**Comment by rk700** [comment]
应该和垃圾回收有关

可以先尝试使用YAHFA的gc分支，看是否有同样问题

**Comment by ws15621066586** [comment]
还有一些，只要HOOK那个方法，就报下面的错（下面摘的片段）：
11-05 11:58:19.679 19245-18992/? A/google-breakpad: -----BEGIN BREAKPAD MICRODUMP-----
11-05 11:58:19.679 19245-18992/? A/google-breakpad: V WebView:46.0.2490.76
11-05 11:58:19.679 19245-18992/? A/google-breakpad: O A arm 08 armv8l OPPO/A57/A57:6.0.1/MMB29M/1487592392:user/release-keys
11-05 11:58:19.679 19245-18992/? A/google-breakpad: S 0 FFB3E480 FFB3E000 00004000
11-05 11:58:19.693 19245-18992/? A/google-breakpad: S FFB3E000 72010000C00E19F7002534F5
..............................

11-05 11:58:19.718 19245-18992/? A/google-breakpad: M AB123000 00000000 0000C000 A57CA2EFEF575ABD64564B831391D0070 app_process32_xposed
11-05 11:58:19.718 19245-18992/? A/google-breakpad: M D9B9F000 00000000 000DB000 1C2BDB85D3BFDC6CAA7093C86D6E50C90 libmmparser_lite.so
11-05 11:58:19.718 19245-18992/? A/google-breakpad: M DE589000 00A08000 01B61000 8E20499B067E9097C5660A31591DD83F0 libwebviewchromium.so
...............................
11-05 11:58:19.745 18992-18992/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x24 in tid 18992 (.mobile.android)
11-05 11:58:19.801 723-723/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-05 11:58:19.801 723-723/? A/DEBUG: Build fingerprint: 'OPPO/A57/A57:6.0.1/MMB29M/1487592392:user/release-keys'
11-05 11:58:19.801 723-723/? A/DEBUG: Revision: '0'
11-05 11:58:19.801 723-723/? A/DEBUG: ABI: 'arm'
11-05 11:58:19.802 723-723/? A/DEBUG: pid: 18992, tid: 18992, name: .mobile.android  >>> com.dada.mobile.android <<<
11-05 11:58:19.802 723-723/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x24
11-05 11:58:19.875 723-723/? A/DEBUG:     r0 00000000  r1 1312a1c0  r2 00000000  r3 00000000
11-05 11:58:19.875 723-723/? A/DEBUG:     r4 00000000  r5 13a30c00  r6 13a2f800  r7 1312a1c0
11-05 11:58:19.875 723-723/? A/DEBUG:     r8 13a31400  r9 f5342500  sl 70fdc990  fp 13a30000
11-05 11:58:19.875 723-723/? A/DEBUG:     ip f73836e9  sp ffb3e480  lr 746285a9  pc dbffa440  cpsr 000e0030
11-05 11:58:19.876 723-723/? A/DEBUG: backtrace:
11-05 11:58:19.876 723-723/? A/DEBUG:     #00 pc 01f13440  /data/app/com.dada.mobile.android-2/oat/arm/base.odex (offset 0x1433000)
11-05 11:58:19.876 723-723/? A/DEBUG:     #01 pc 746285a7  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x2287000)
11-05 11:58:21.019 723-723/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_03
11-05 11:58:21.019 723-723/? E/DEBUG: AM write failed: Broken pipe
