### ISSUE TITLE
插件apk里面可以有Activity吗

### ISSUE THREAD

**Issue by libingwei** [rk700/VirtualHook#48]
我在你的一个ChangePhoneInfo示例插件里加入了一个Activity之后测试，点击之后开启时从日志看好像陷入了循环，启动不了； 是本来机制不支持吗？
我想要插件提供一个界面，以便自定义设置一些参数给底层Hook处理时使用，可否实现？

**Comment by rk700** [comment]
可以，插件可以写成一个带activity的正常app单独启动，包含预先约定的hook items信息就也可以被加载做hook
