### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by wjy000** [rk700/VirtualHook#5]
Error:Execution failed for task ':app:transformClassesWithRetrolambdaForDebug'.
> Missing javaCompileTask for variant: debug/0 from output dir: C:\Users\Administrator\Desktop\Test\VirtualHook\VirtualApp\app\build\intermediates\transforms\retrolambda\debug\0

之前版本clone可以运行,最新一次clone后总是无法运行,提示这个错误

**Comment by rk700** [comment]
无法编译？清一下环境吧
