### ISSUE TITLE
Can you give Compiled apk??

### ISSUE THREAD

**Issue by SciFi1818** [rk700/VirtualHook#52]
Hello
Can you give me the Compiled apk of this project??
As I am unable to Compile the native library due to some issue, I couldn't enjoy this master piece..if you can give me the Compiled apk , it would be so helpful..

**Comment by rk700** [comment]
Rename it to app-debug.apk:
[app-debug.zip](https://github.com/rk700/VirtualHook/files/1574045/app-debug.zip)

**Comment by SciFi1818** [comment]
Thanks a lot
