### ISSUE TITLE
关于backup方法

### ISSUE THREAD

**Issue by AllenMeex** [rk700/VirtualHook#56]
请教下大神，demo里backup方法的返回值为什么是null？这个返回值跟被hook的原始方法返回值有什么关系？

public class Hook_AssetManager_open {
    public static String className = "android.content.res.AssetManager";
    public static String methodName = "open";
    public static String methodSig = "(Ljava/lang/String;)Ljava/io/InputStream;";
    public static InputStream hook(Object thiz, String fileName) {
        Log.w("YAHFA", "open asset "+fileName);
        return backup(thiz, fileName);
    }

    public static InputStream backup(Object thiz, String msg) {
        Log.w("YAHFA", "should not be here");
        return null;
    }
}

像这个demo里，不理解为什么hook方法里直接retrun backup方法，不就是直接返回了null么，这样open返回不就永远是null了么为什么程序还能正常运行？

我现在想hook一个方法，像xposed那样先获取到原始方法返回值，修改部分内容后返回给程序，应该怎样做呢？

谢谢

**Comment by rk700** [comment]
`backup()`只是占位用的，其内容在hook时会被替换为原方法，因此调用`backup()`实际执行的内容仍然是原方法

如果要修改原方法返回值，在`hook()`中直接调用`backup()`，再对`backup()`的返回结果修改，最后在`hook()`中return修改后的结果即可

**Comment by AllenMeex** [comment]
可以了~谢谢大神~
