### ISSUE TITLE
hook native 方法，在android6上表现正常，在7上某些方法不能使用

### ISSUE THREAD

**Issue by scucsxn** [rk700/VirtualHook#58]
1. namespace Cydia{
    void MSHookFunction(void *symbol, void *replace, void **result);
}

2. imageHandle =  dlopen("/system/lib/libmedia.so", RTLD_GLOBAL | RTLD_NOW);
dlsym(imageHandle, symbol);
MSHookFunction(address, replace, result); 
在android6中会进入到hook的函数，在android 7无效

**Comment by rk700** [comment]
应该与VirtualApp的so文件改名有关

https://github.com/rk700/VirtualHook/commit/ea151900e140a123e6bab627d24b021d533ed9cd

**Comment by scucsxn** [comment]
但是这个在android os 6中是可以的，在android os7就不行了，请问大佬这个该怎么解决呢？能稍微具体点吗

**Comment by rk700** [comment]
可以试下前面链接里的最新commit

**Comment by scucsxn** [comment]
还是不行。已经试过了。
1."/system/lib/libOpenSLES.so" ，hook这个so， android6，7都可以。
2."/system/lib/libmedia.so"， hook这个so, android 6可以，android 7不可以

**Comment by rk700** [comment]
https://developer.android.com/about/versions/nougat/android-7.0-changes.html?hl=zh-cn#ndk

7.0禁止链接非公开库

**Comment by scucsxn** [comment]
那在7.0上想使用imageHandle = dlopen("/system/lib/libmedia.so", RTLD_GLOBAL | RTLD_NOW);就没有办法了吗
