### ISSUE TITLE
自己集成遇到的问题

### ISSUE THREAD

**Issue by wjy000** [rk700/VirtualHook#6]
大神,除了在VClientImpl中注入插件,还有没有其他地方的修改?我用你的demo可以成功hook,但是自己弄的时候,虽然打印了hook信息,但是实际上并没有成功hook

**Comment by wjy000** [comment]
我用了你项目的 lib 和 YAHFA就可以了,但是我想知道你修改了va的哪些内容,如果方便的话可以指导一下小弟吗?

**Comment by rk700** [comment]
va本身没有做什么修改，就是在VClientImpl中注入hook。具体可以对比下两者的代码
