### ISSUE TITLE
HOOK VirtualHook 里面启动的app失败

### ISSUE THREAD

**Issue by hulovebin** [rk700/VirtualHook#61]
public class Hook_SQLiteDatabase_insert {
    //com.tencent.wcdb.database.SQLiteDatabase
    public static String className = "com.tencent.wcdb.database.SQLiteDatabase";
    public static String methodName = "insert";
    public static String methodSig = "(Ljava/lang/String;Ljava/lang/String;Landroid/content/ContentValues;)long";

    public static long hook(Object thiz,String arg1, String arg2,ContentValues arg3) {
        Log.w("zb0011", "SQLiteDatabase arg1:"+arg1 + "arg2:"+arg1);
        return origin(thiz,arg1, arg2,arg3);
    }

    public static long origin(Object thiz,String arg1, String arg2,ContentValues arg3) {
        Log.w("zb0011", "should not be here");
        return 1;
    }
}

//jeb 里面的被 hook 方法 代码
public final long insert(String arg6, String arg7, ContentValues arg8) {
        long v0_2;
        try {
            v0_2 = this.insertWithOnConflict(arg6, arg7, arg8, 0);
        }
        catch(SQLException v0) {
            Log.e("WCDB.SQLiteDatabase", "Error inserting %s: %s", new Object[]{arg8, v0});
            v0_2 = -1;
        }
        catch(SQLiteDatabaseCorruptException v0_1) {
            throw v0_1;
        }

        return v0_2;
    }
//++++++++++++++++++++++++++++++++++++++
//log
01-16 10:43:48.735  8366  8366 E YAHFA   : hello world from jni
01-16 10:43:48.735  8366  8366 I YAHFA   : Start hooking with item lab.galaxy.demeHookPlugin.Hook_SQLiteDatabase_insert
01-16 10:43:48.753  8366  8366 D YAHFA   : target method param count is 3
01-16 10:43:48.754  8366  8366 I YAHFA-Native: Start findAndBackupAndHook for non-static method insert(Ljava/lang/String;Ljava/lang/String;Landroid/content/ContentValues;)long
01-16 10:43:48.754  8366  8366 E YAHFA-Native: Cannot find target non-static method: insert(Ljava/lang/String;Ljava/lang/String;Landroid/content/ContentValues;)long
01-16 10:43:48.754  8366  8366 I YAHFA   : Start hooking with item lab.galaxy.demeHookPlugin.Hook_AssetManager_open
01-16 10:43:48.756  8366  8366 D YAHFA   : target method param count is 1
01-16 10:43:48.756  8366  8366 I YAHFA-Native: Start findAndBackupAndHook for non-static method open(Ljava/lang/String;)Ljava/io/InputStream;
01-16 10:43:48.756  8366  8366 W YAHFA-Native: not enough capacity. Allocating...
01-16 10:43:48.756  8366  8366 I YAHFA-Native: Allocating done
01-16 10:43:48.756  8366  8366 I YAHFA-Native: target method is at 0x6fb6536c, hook method is at 0xcb6431e0, backup method is at 0xcb6431bc
01-16 10:43:48.756  8366  8366 I YAHFA-Native: hook and backup done
01-16 10:43:49.393  8366  8399 W YAHFA   : open asset estrings/encrypt.mmstrid

**Comment by rk700** [comment]
`long`的signature有误：https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/types.html#wp276

**Comment by hulovebin** [comment]
多谢解答，谢谢。
