### ISSUE TITLE
希望可以更新一下VirtualApp的版本

### ISSUE THREAD

**Issue by wjy000** [rk700/VirtualHook#7]
我自己更新到VirtualApp最新版总是无法成功hook java函数,用你目前版本的就没问题,但是你目前用的VirtualApp版本有点旧了,做so hook不方便,希望可以更新一下,期待中...

**Comment by rk700** [comment]
VirtualHook会不定期与上游的VirtualApp进行代码合并，目前仅落后VirtualApp 2个commits，此外还做了一些修改：

https://github.com/asLody/VirtualApp/compare/master...rk700:master
