### ISSUE TITLE
Cannot find hook for getDeviceId

### ISSUE THREAD

**Issue by TinyNiko** [rk700/VirtualHook#72]
public static String className = "android.telephony.TelephonyManager";
    public static String methodName = "getDeviceId";
    public static String methodSig = "()Ljava/lang/String;";
    public  String hook() {
        Log.e("YAHFA", "in imei");
        return "11111111111111";
    }

    public  String backup() {
        Log.e("YAHFA", "2333");
        return "";
    }
 代码如上

**Comment by rk700** [comment]
手机和系统是什么，hook的app是什么？

getDeviceId是non-static，方法需要传入this Object

https://github.com/rk700/ChangePhoneInfo/blob/master/app/src/main/java/lab/galaxy/changephoneinfo/Hook_TelephonyManager_getDeviceId.java
