### ISSUE TITLE
Hook android.hardware.Camera::takePicture失败

### ISSUE THREAD

**Issue by zxfbuptmmcgmailcom** [rk700/VirtualHook#75]
非常感谢这么优秀的hook'框架。
我在尝试Hook Camera的takePicture方法时失败了，不知您是否碰到过类似情况？具体步骤如下:
Hook代码:

import android.hardware.Camera;
import android.util.Log;
public class Camera_Hook_takePicture {

    public static String className = "android.hardware.Camera";
    public static String methodName = "takePicture";
    public static String methodSig = "(Landroid/hardware/Camera$ShutterCallback;Landroid/hardware/Camera$PictureCallback;Landroid/hardware/Camera$PictureCallback;)V";

    public static void hook(Object thiz, Camera.ShutterCallback arg1, Camera.PictureCallback arg2, Camera.PictureCallback arg3) {
        Log.i("YAHFA", "Camera_Hook_takePicture hooked");
        backup(thiz,arg1,arg2,arg3);
    }

    public static void backup(Object thiz, Camera.ShutterCallback arg1, Camera.PictureCallback arg2, Camera.PictureCallback arg3) {
        Log.i("YAHFA", "just a placeholder, should not be here");
        return;
    }
}

hook初始化过程中没有看到任何错误，而且最后的Native Log也显示hook完成:
05-31 16:37:24.212 10868-10868/io.virtualhook:p0 I/YAHFA-Native: Start findAndBackupAndHook for non-static method takePicture(Landroid/hardware/Camera$ShutterCallback;Landroid/hardware/Camera$PictureCallback;Landroid/hardware/Camera$PictureCallback;)V
    target method is at 0x703fbc20, hook method is at 0x8750e640, backup method is at 0x8750e5a0
    hook and backup done

但在实际hook一个takePicture例子时并没有打印出 "Camera_Hook_takePicture hooked"，说明hook没有成功。
takePicture正常工作，能拍照。

尝试过您提供的例子，里面的API Hook都能成功。

不知有谁也碰到类似问题？ 谢谢大家!
我用的是三星Galaxy S5, android5.0

**Comment by zxfbuptmmcgmailcom** [comment]
不知道是不是因为Camera类里有两个名为takePicture的方法造成的? 
他们的调用关系是:
     takePicture(ShutterCallback arg1, PictureCallback arg2,PictureCallback arg3)
     调用  takePicture(ShutterCallback arg1, PictureCallback arg2, PictureCallback arg3,PictureCallback arg4)
     后面那个带有四个参数的takePicture再调用 native_takePicture(int msgType)
我hook native_takePicture方法是能成功的。

**Comment by zxfbuptmmcgmailcom** [comment]
同样问题发生在hook Bitmap::createBitmap 方法时：
Bitmapy也有多个方法名叫createBitmap， 而且也是相互调用。

public class Hook_Bitmap_createBitmap {

    public static String className = "android.graphics.Bitmap";
    public static String methodName = "createBitmap";
    public static String methodSig = "(Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;";


    public static Bitmap hook(Bitmap src) {
        Log.e("YAHFA", "Bitmap_createBitmap hooked");
        return backup(src);
    }

    public static Bitmap backup(Bitmap src) {
        Log.e("YAHFA", "just a placeholder, should not be here");
        return null;
    }
}

**Comment by rk700** [comment]
可能与5.0上dex2oat的编译优化有关

https://github.com/rk700/YAHFA/issues/2

**Comment by zxfbuptmmcgmailcom** [comment]
dump了一下oat，的确是直接就调到固定地址了。
      0x00077890: 4683    	mov     r11, r0
      0x00077892: f64e0ed1	movw    lr, #59601
      0x00077896: f2c74ecf	movt    lr, #29903
      0x0007789a: f2473040	movw    r0, #29504
      0x0007789e: f2c7003c	movt    r0, #28732
      0x000778a2: 4659    	mov     r1, r11
      0x000778a4: 47f0    	blx     lr
可能是因为我hook的那个createBitmap只是简单的调用了另外一个createBitmap。
我试了一下去hook带有很多逻辑代码的createBitmap的方法是可以成功的。

非常感谢！
