### ISSUE TITLE
请问hook函数中的由被hook应用提供的自定义类型如何给定?

### ISSUE THREAD

**Issue by zjzdy** [rk700/VirtualHook#8]
例如说我想要hook一个methodSig 为`(Landroid/app/Application;Lcom/c/d/e/f/Configuration;)Lcom/c/d/e/f/g;`的类.
在xposed框架中可以用类似
`final Class<?> Configuration= XposedHelpers.findClass("com.c.d.e.f.Configuration", loadPackageParam.classLoader);`的方法来给定自定义类型.
在yahfa中没找到相关方法,只是在`HookMain.java`中找到`Class<?> clazz = Class.forName(className, true, originClassLoader);`,但hook插件中拿不到ClassLoader.
请问这种自定义类型如何给定?

**Comment by rk700** [comment]
xposed中需要指定hook目标方法的每个参数的类。yahfa里面做hook，只需要指定目标方法的signature字符串就行，不需要通过反射去得到类

**Comment by zjzdy** [comment]
那hook函数该怎么写？
还是直接写成这样
```
    public static Object hook(Object thiz, Application a,Object c) {
        return origin(thiz, a,c);
    }
```
总感觉不对啊。
特别是如果我想对传入的Configuration类对象进行一些操作，或者想新建一个新的Configuration对象来代替原来的对象传入原方法，不知怎么动手啊。

**Comment by rk700** [comment]
你可以通过反射拿到这个对象的类：
```java
    public static Object hook(Object thiz, Application a,Object c) {
        Class confClass = c.getClass();
        return origin(thiz, a,c);
    }
```
其他操作可以继续通过反射完成

如果需要新建一个Configuration对象，那还是通过反射拿到类的构造函数，再把新建的对象传给`origin()`:
```java
    public static Object hook(Object thiz, Application a,Object c) {
        Object newConf = ...;
        return origin(thiz, a, newConf);
    }
```

**Comment by zjzdy** [comment]
意思就是传递参数时可以直接用Object来代替自定义类（对象），不会对函数的匹配造成影响；而对这个的对象的操作则全部通过反射完成。对吧？
谢谢。
