### ISSUE TITLE
如果在hook后的app里面接收系统广播？

### ISSUE THREAD

**Issue by callmemaha** [rk700/VirtualHook#95]
我这边发现hook后的app，无法接收到非hook的app发送的广播。如何才能接收到这个广播？或者在VirtualHook的什么位置去转发这个广播？

**Comment by rk700** [comment]
可以先排查下不进行hook是否可以正常接受广播

**Comment by callmemaha** [comment]
广播功能都是正常的
我后面再hookapp那里做了个广播转发
VActivityManager.get().sendBroadcast(intent, VUserHandle.myUserId());
已解决。
